image: openjdk:8-jdk

variables:
  GODOT_ZIP: "godot_3.2.2-beta4_linux_headless.zip"
  GODOT_EXC: "godot_editor/Godot_v3.2.2-beta4_linux_headless.64"
  GODOT_DOWNLOAD_URL: "https://downloads.tuxfamily.org/godotengine/3.2.2/beta4/Godot_v3.2.2-beta4_linux_headless.64.zip"

before_script:
  - pwd
  - export DOCKER_HOME=$PWD
  - export GODOT_VERSION=3.2.2-beta4
  # Locale must be set or else it will cause additional errors for Godot 
  - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y locales
  - sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
  - dpkg-reconfigure --frontend=noninteractive locales
  - update-locale LANG=en_US.UTF-8
  - export LANG=en_US.UTF-8
  - mkdir -p ~/.config/godot/projects
  - mkdir -p ~/.godot
  - mkdir -p ~/.local/share/godot
  - mkdir -p ~/.config/godot
  - mkdir -p ~/.cache
  - cp $DOCKER_HOME/.gitlab/ci_scripts/editor_settings-3.tres ~/.config/godot/editor_settings-3.tres

stages:
  - unit_test
  - integration_test
  - multiplayer_unit_test
  - multiplayer_integration_test
  - build_for_android

unit_tests:
  stage: unit_test
  variables:
    DEBIAN_FRONTEND: noninteractive
  script:
    - wget --quiet --output-document=$GODOT_ZIP $GODOT_DOWNLOAD_URL
    - ls -a
    - unzip -q -d godot_editor $GODOT_ZIP
    - ls -a godot_editor
    - chmod +x $GODOT_EXC
    - python3 $DOCKER_HOME/godot/tests/run_unit_tests.py

integration_tests:
  stage: integration_test
  script:
    - wget --quiet --output-document=$GODOT_ZIP $GODOT_DOWNLOAD_URL
    - unzip -q -d godot_editor $GODOT_ZIP
    - chmod +x $GODOT_EXC
    - python3 $DOCKER_HOME/godot/tests/run_integration_tests.py

multiplayer_unit_tests:
  stage: multiplayer_integration_test
  script:
    - wget --quiet --output-document=$GODOT_ZIP $GODOT_DOWNLOAD_URL
    - unzip -q -d godot_editor $GODOT_ZIP
    - chmod +x $GODOT_EXC
    - python3 $DOCKER_HOME/godot/tests/run_multiplayer_unit_tests.py

multiplayer_integration_tests:
  stage: multiplayer_integration_test
  script:
    - wget --quiet --output-document=$GODOT_ZIP $GODOT_DOWNLOAD_URL
    - unzip -q -d godot_editor $GODOT_ZIP
    - chmod +x $GODOT_EXC
    - python3 $DOCKER_HOME/godot/tests/run_multiplayer_integration_tests.py

build_apk:
  stage: build_for_android
  script:
    - wget --quiet --output-document=$GODOT_ZIP $GODOT_DOWNLOAD_URL
    - wget --quiet --output-docuemnt=GodotExportTemplates.tpz
    - unzip -q -d godot_editor $GODOT_ZIP
    - unzip -q -d ~/.local/share/godot GodotExportTemplates.tpz
    - ls -a ~/.local/share/godot
    - chmod +x $GODOT_EXC
    - $GODOT_EXC --path godot --export-debug Android FreecoiL.apk
  artifacts:
    paths:
    - Freecoil.apk
    expire_in: 1 week
