image: openjdk:8-jdk

variables:
  GODOT_VERSION: "3.1-alpha2"

before_script:
  - pwd
  - export DOCKER_HOME=$PWD
  # Locale must be set or else it will cause additional errors for Godot 
  - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y locales
  - sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
  - dpkg-reconfigure --frontend=noninteractive locales
  - update-locale LANG=en_US.UTF-8
  - export LANG=en_US.UTF-8
  - mkdir -p ~/.config/godot/projects
  - mkdir -p ~/.godot
  - mkdir -p ~/.local/share/godot
  - mkdir -p ~/.config/godot
  - mkdir -p ~/.cache
  - cp $DOCKER_HOME/.gitlab/ci_scripts/editor_settings-3.tres ~/.config/godot/editor_settings-3.tres

stages:
  - automated_tests

unit_tests:
  stage: automated_tests
  variables:
    DEBIAN_FRONTEND: noninteractive
  script:
    # Download Server version of Godot
    - wget --quiet --output-document=godot_3.1_server.zip https://downloads.tuxfamily.org/godotengine/3.1/alpha2/Godot_v3.1-alpha2_linux_server.64.zip
    - unzip -q -d godot_editor godot_3.1_server.zip
    - chmod +x $DOCKER_HOME/godot_editor/Godot_v3.1-alpha2_linux_server.64
    - $DOCKER_HOME/godot_editor/Godot_v3.1-alpha2_linux_server.64 -s $DOCKER_HOME/godot/tests/RunUnitTests.gd --path $DOCKER_HOME/godot/

integration_tests:
  stage: automated_tests
  script:
    # Download Headless version of Godot
    - wget --quiet --output-document=godot_3.1_linux_headless.zip https://downloads.tuxfamily.org/godotengine/3.1/alpha2/Godot_v3.1-alpha2_linux_headless.64.zip
    - unzip -q -d godot_editor godot_3.1_linux_headless.zip
    - chmod +x $DOCKER_HOME/godot_editor/Godot_v3.1-alpha2_linux_headless.64
    - export FreecoiL_TEST=true
    - $DOCKER_HOME/godot_editor/Godot_v3.1-alpha2_linux_headless.64 --path $DOCKER_HOME/godot/

2player_integration_tests:
  stage: automated_tests
  script:
    # Download Headless version of Godot. Don't use the server version in these tests.
    - wget --quiet --output-document=godot_3.1_linux_headless.zip https://downloads.tuxfamily.org/godotengine/3.1/alpha2/Godot_v3.1-alpha2_linux_headless.64.zip
    - unzip -q -d godot_editor godot_3.1_linux_headless.zip
    - chmod +x $DOCKER_HOME/godot_editor/Godot_v3.1-alpha2_linux_headless.64
    - export FreecoiL_2PLAYER_TEST=true
    - $DOCKER_HOME/godot_editor/Godot_v3.1-alpha2_linux_headless.64 --path $DOCKER_HOME/godot/ &
    # We start the server last. The clients will wait. Server will print all details to stdout.
    # Since Godot's networking is Server Centric this makes the most sense.
    - export FreecoiL_SERVER=true
    - $DOCKER_HOME/godot_editor/Godot_v3.1-alpha2_linux_headless.64 --path $DOCKER_HOME/godot/ 
    - export FreecoiL_SERVER=false

multiplayer_integration_tests:
  stage: automated_tests
  script:
    # Download Headless version of Godot. Don't use the server version in these tests.
    - wget --quiet --output-document=godot_3.1_linux_headless.zip https://downloads.tuxfamily.org/godotengine/3.1/alpha2/Godot_v3.1-alpha2_linux_headless.64.zip
    - unzip -q -d godot_editor godot_3.1_linux_headless.zip
    - chmod +x $DOCKER_HOME/godot_editor/Godot_v3.1-alpha2_linux_headless.64
    - export FreecoiL_MULTIPLAYER_TEST=true
    - $DOCKER_HOME/godot_editor/Godot_v3.1-alpha2_linux_headless.64 --path $DOCKER_HOME/godot/ &
    # We start the server last. The clients will wait. Server will print all details to stdout.
    # Since Godot's networking is Server Centric this makes the most sense.
    - export FreecoiL_SERVER=true
    - $DOCKER_HOME/godot_editor/Godot_v3.1-alpha2_linux_headless.64 --path $DOCKER_HOME/godot/ 
    - export FreecoiL_SERVER=false