image: myood/godot-ci-android-export:godot-3.2.2-beta4

#https://github.com/myood/godot-ci-android-export
#https://github.com/myood/godot-ci-android-export/blob/master/.gitlab-ci.yml
#https://hub.docker.com/r/myood/godot-ci-android-export/tags

variables:
  APP_NAME: "FreecoiL"

before_script:
  - export DOCKER_HOME=$PWD
  - apt-get update
  - apt-get install -y python3
  - mkdir -p ~/.config/godot/projects
  - mkdir -p ~/.godot
  - mkdir -p ~/.local/share/godot
  - mkdir -p ~/.config/godot
  - mkdir -p ~/.cache
  - cp $DOCKER_HOME/.gitlab/ci_scripts/editor_settings-3.tres ~/.config/godot/editor_settings-3.tres

stages:
  - unit_test
  - integration_test
  - multiplayer_unit_test
  - multiplayer_integration_test
  - build_for_android

unit_tests:
  stage: unit_test
  variables:
    DEBIAN_FRONTEND: noninteractive
  script:
    - python3 $DOCKER_HOME/godot/tests/run_unit_tests.py

integration_tests:
  stage: integration_test
  script:
    - python3 $DOCKER_HOME/godot/tests/run_integration_tests.py

multiplayer_unit_tests:
  stage: multiplayer_integration_test
  script:
    - python3 $DOCKER_HOME/godot/tests/run_multiplayer_unit_tests.py

multiplayer_integration_tests:
  stage: multiplayer_integration_test
  script:
    - python3 $DOCKER_HOME/godot/tests/run_multiplayer_integration_tests.py

build_apk:
  stage: build_for_android
  script:
    # This is simply (semi-manual :-)) double-check if editor settings are OK for debug export
    - grep android ~/.config/godot/editor_settings-3.tres
    - ls -l /usr/lib/jvm/java-8-openjdk-amd64/bin/jarsigner
    - ls -l /root/android/debug.keystore
    - ls -l /root/android/platform-tools/adb
    - ls -a /root/.local/share/godot/templates/3.2.2.beta4
    # Create directory for artifacts
    - mkdir -v -p export/android
    - awk '/const VERSION = "/{print $NF}' godot/code/Settings.gd
    - godot --path godot/project.godot --export-debug "Android" ../export/android/${APP_NAME}-debug.apk
    - ls export/android/${APP_NAME}-debug.apk # ls
    - ls -a export/android/
  artifacts:
    name: ${APP_NAME}-debug
    paths:
      - export/android/${APP_NAME}-debug.apk
    expire_in: 1 week
